name: ExpMoney
version: ${project.version}${describe}
description: Vault interface that uses experience
authors: [meiskam, killermantime]

main: org.shininet.bukkit.expmoney.ExpMoney
database: false

depend: [Vault]

commands:
  ExpMoney:
    description: GIMMEH MAH MONEY
    aliases: money