name: ExpCurrency
version: ${project.version}${describe}
description: Vault interface that uses experience
authors: [meiskam, killermantime]

main: org.shininet.bukkit.expcurrency.ExpCurrency
database: false

depend: [Vault]

commands:
  ExpCurrency:
    description: GIMMEH MAH MONEY
    aliases: money